# Placement Prediction Model


In [1]:
import pandas as pd
dataset = pd.read_csv("data.csv")

In [2]:
old_min = dataset['Probability'].min()
old_max = dataset['Probability'].max()

new_min = 50
new_max = 95

dataset['Probability2'] = ((dataset['Probability'] - old_min) / (old_max - old_min)) * (new_max - new_min) + new_min



In [3]:
dataset.head()

Tenth  Twelfth  CGPA  Internships  Projects  Aptitude  Soft skills  \
0  79.97    60.04   NaN            1         2     62.82        22.40   
1  73.62    77.76  6.87            1         0     42.10        73.96   
2  81.48    85.22  8.15            1         5     56.08        54.59   
3  90.23    81.31  7.07            1         2     71.85        89.45   
4  72.66    84.93  7.94            1         2     58.22        82.04   

   Leadership  Extracurricular  Certifications  Backlogs    DSA  Lang  \
0       64.73            41.01               2         1  31.82     2   
1       62.72            17.85               1         0  59.50     3   
2       69.44            62.06               1         1  65.57     2   
3       69.47            44.74               0         1  26.38     3   
4       74.46            52.91               2         0  66.35     1   

   Probability  Probability2  
0         46.4     71.093040  
1         52.7     73.956965  
2         60.4     77.457319  
3         58.4     76.548136  
4         60.9     77.684615

In [4]:
dataset.tail()


Tenth  Twelfth  CGPA  Internships  Projects  Aptitude  Soft skills  \
11002    0.0      0.0   0.0            0         0       0.0          0.0   
11003    0.0      0.0   0.0            0         0       0.0          0.0   
11004  100.0    100.0  10.0           10        10     100.0        100.0   
11005  100.0    100.0  10.0           10        10     100.0        100.0   
11006  100.0    100.0  10.0           10        10     100.0        100.0   

       Leadership  Extracurricular  Certifications  Backlogs    DSA  Lang  \
11002         0.0              0.0               0         0    0.0     0   
11003         0.0              0.0               0         0    0.0     0   
11004       100.0            100.0              10        10  100.0    10   
11005       100.0            100.0              10        10  100.0    10   
11006       100.0            100.0              10        10  100.0    10   

       Probability  Probability2  
11002         0.00     50.000000  
11003         0.00     50.000000  
11004        98.99     95.000000  
11005        98.78     94.904536  
11006        98.85     94.936357

In [5]:
dataset.head(500)


Tenth  Twelfth  CGPA  Internships  Projects  Aptitude  Soft skills  \
0    79.97    60.04   NaN            1         2     62.82        22.40   
1    73.62    77.76  6.87            1         0     42.10        73.96   
2    81.48    85.22  8.15            1         5     56.08        54.59   
3    90.23    81.31  7.07            1         2     71.85        89.45   
4    72.66    84.93  7.94            1         2     58.22        82.04   
..     ...      ...   ...          ...       ...       ...          ...   
495  80.39    72.37  6.51            2         1     77.56        75.03   
496  64.63    67.77  5.62            0         3     55.59        63.40   
497  73.10    65.70  6.20            0         2     67.28        61.51   
498  66.24    70.35  6.86            1         1     53.37        71.17   
499  61.17    68.23  7.35            1         1     47.04        64.12   

     Leadership  Extracurricular  Certifications  Backlogs    DSA  Lang  \
0         64.73            41.01               2         1  31.82     2   
1         62.72            17.85               1         0  59.50     3   
2         69.44            62.06               1         1  65.57     2   
3         69.47            44.74               0         1  26.38     3   
4         74.46            52.91               2         0  66.35     1   
..          ...              ...             ...       ...    ...   ...   
495       38.39            41.85               0         0  66.32     3   
496       61.31            93.60               1         0  66.92     1   
497       66.15            43.20               2         0  48.70     3   
498       38.38            83.39               1         0  46.10     6   
499       87.40            50.73               0         0  70.61     3   

     Probability  Probability2  
0           46.4     71.093040  
1           52.7     73.956965  
2           60.4     77.457319  
3           58.4     76.548136  
4           60.9     77.684615  
..           ...           ...  
495         55.7     75.320739  
496         51.8     73.547833  
497         52.5     73.866047  
498         54.4     74.729771  
499         54.7     74.866148  

[500 rows x 15 columns]

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11007 entries, 0 to 11006
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Tenth            11007 non-null  float64
 1   Twelfth          11007 non-null  float64
 2   CGPA             11006 non-null  float64
 3   Internships      11007 non-null  int64  
 4   Projects         11007 non-null  int64  
 5   Aptitude         11007 non-null  float64
 6   Soft skills      11007 non-null  float64
 7   Leadership       11007 non-null  float64
 8   Extracurricular  11007 non-null  float64
 9   Certifications   11007 non-null  int64  
 10  Backlogs         11007 non-null  int64  
 11  DSA              11007 non-null  float64
 12  Lang             11007 non-null  int64  
 13  Probability      11007 non-null  float64
 14  Probability2     11007 non-null  float64
dtypes: float64(10), int64(5)
memory usage: 1.3 MB


In [7]:
dataset.describe()

Tenth       Twelfth          CGPA   Internships      Projects  \
count  11007.000000  11007.000000  11006.000000  11007.000000  11007.000000   
mean      74.903997     73.132398      6.983860      1.008813      1.987917   
std       10.050622     11.051782      1.005211      0.997733      1.413744   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%       68.230000     65.720000      6.300000      0.000000      1.000000   
50%       74.920000     73.190000      6.990000      1.000000      2.000000   
75%       81.670000     80.680000      7.670000      2.000000      3.000000   
max      100.000000    100.000000     10.000000     10.000000     10.000000   

           Aptitude   Soft skills    Leadership  Extracurricular  \
count  11007.000000  11007.000000  11007.000000     11007.000000   
mean      69.982285     67.722211     64.950130        59.724735   
std       14.682235     14.866404     19.188491        19.573598   
min        0.000000      0.000000      0.000000         0.000000   
25%       60.225000     57.860000     51.855000        46.475000   
50%       70.050000     67.790000     65.450000        59.850000   
75%       79.975000     78.000000     78.690000        73.100000   
max      100.000000    100.000000    100.000000       100.000000   

       Certifications      Backlogs           DSA          Lang   Probability  \
count    11007.000000  11007.000000  11007.000000  11007.000000  11007.000000   
mean         1.005451      0.507859     64.824504      2.009358     56.752932   
std          1.005874      0.732855     19.283021      1.428279      4.317834   
min          0.000000      0.000000      0.000000      0.000000      0.000000   
25%          0.000000      0.000000     51.805000      1.000000     54.000000   
50%          1.000000      0.000000     64.790000      2.000000     56.800000   
75%          2.000000      1.000000     78.520000      3.000000     59.600000   
max         10.000000     10.000000    100.000000     10.000000     98.990000   

       Probability2  
count  11007.000000  
mean      75.799393  
std        1.962850  
min       50.000000  
25%       74.547934  
50%       75.820790  
75%       77.093646  
max       95.000000

In [8]:
dataset['Projects'].value_counts()

Projects
1     3049
2     3033
3     1896
0     1466
4     1005
5      377
6      123
7       44
10       5
9        5
8        4
Name: count, dtype: int64

In [9]:
%matplotlib inline

In [10]:
import matplotlib.pyplot as plt

In [11]:
#dataset.hist(bins=50, figsize=(20,15), color="indigo")

## Train - Test Split 

In [12]:
import numpy as np
def split_train_test(data,test_ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    print(shuffled)
    test_set_size = int(len(data)*test_ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices] 


In [13]:
train_set, test_set =  split_train_test(dataset,0.2)
print(f"rows in test set: {len(test_set)}")
print(f"rows in train set: {len(train_set)}")

[ 107 5487 1870 ... 5390  860 7270]
rows in test set: 2201
rows in train set: 8806


In [14]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(dataset, dataset['Projects']):
    strat_train_set = dataset.loc[train_index]
    strat_test_set = dataset.loc[test_index]

In [15]:
strat_test_set['Projects'].value_counts()


Projects
1     610
2     607
3     379
0     293
4     201
5      75
6      25
7       9
8       1
10      1
9       1
Name: count, dtype: int64

In [16]:
strat_train_set['Projects'].value_counts()

Projects
1     2439
2     2426
3     1517
0     1173
4      804
5      302
6       98
7       35
10       4
9        4
8        3
Name: count, dtype: int64

In [17]:
dataset = strat_train_set.copy()

## Looking for Correlations

In [18]:
corr_matrix = dataset.corr(numeric_only=True)


In [19]:
corr_matrix['Probability2'].sort_values(ascending=False)

Probability        1.000000
Probability2       1.000000
CGPA               0.454946
Leadership         0.375151
Twelfth            0.339114
Tenth              0.318120
Soft skills        0.299575
Aptitude           0.299349
DSA                0.296813
Internships        0.257267
Extracurricular    0.245579
Lang               0.231983
Certifications     0.181422
Projects           0.177626
Backlogs          -0.129439
Name: Probability2, dtype: float64

In [20]:
#from pandas.plotting import scatter_matrix
#attributes = ["CGPA", "Probability", "Tenth", "Backlogs"]
#scatter_matrix(dataset[attributes], figsize = (12,8))

In [21]:
#dataset.plot(kind = "scatter", x="CGPA", y="Probability", alpha=0.8)

In [22]:
#dataset.plot(kind = "scatter", x="Projects", y="Probability", alpha=0.8)

In [23]:
#dataset.plot(kind = "scatter", x="Internships", y="Probability", alpha=0.8)

In [24]:
#dataset.plot(kind = "scatter", x="Leadership", y="Probability", alpha=0.8)

In [25]:
#dataset.plot(kind = "scatter", x="Certifications", y="Probability", alpha=0.8)

## Trying new Attribute combinations

In [26]:
#dataset["CGPA/langauges"] = dataset["CGPA"]/dataset["Lang"]

In [27]:
dataset = strat_train_set.drop(["Probability", "Probability2"], axis=1, errors="ignore")


#dataset = strat_train_set.drop("Probability2", axis=1)
#dataset = strat_train_set.drop("Probability", axis=1)
dataset_labels = strat_train_set["Probability2"].copy()

## Missing Attributes

In [28]:
#to take care of missing aatributes
#1. to get rid of the missing datapoints
#2. to get res of the whole attribute 
#3. give the value to the missing datapoint (0,mean,meadian) to calculate this we can use the imputer from sklearn


In [29]:
from sklearn.impute import SimpleImputer
numeric_data = dataset.select_dtypes(include=['int64', 'float64'])
imputer = SimpleImputer(strategy="median")
dataset[numeric_data.columns] = imputer.fit_transform(numeric_data)

In [30]:
imputer.statistics_

array([74.86, 73.23,  6.99,  1.  ,  2.  , 69.92, 67.86, 65.46, 59.79,
        1.  ,  0.  , 64.67,  2.  ])

In [31]:
X = imputer.transform(dataset[numeric_data.columns])

In [32]:
dataset_tr = pd.DataFrame(X, columns = dataset[numeric_data.columns].columns)

In [33]:
dataset_tr.describe()

Tenth      Twelfth         CGPA  Internships     Projects  \
count  8805.000000  8805.000000  8805.000000  8805.000000  8805.000000   
mean     74.835295    73.209646     6.984544     1.011811     1.987621   
std      10.113122    11.062912     1.005210     1.000952     1.413235   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      68.110000    65.840000     6.290000     0.000000     1.000000   
50%      74.860000    73.230000     6.990000     1.000000     2.000000   
75%      81.630000    80.750000     7.670000     2.000000     3.000000   
max     100.000000   100.000000    10.000000    10.000000    10.000000   

          Aptitude  Soft skills   Leadership  Extracurricular  Certifications  \
count  8805.000000  8805.000000  8805.000000      8805.000000     8805.000000   
mean     69.901691    67.818410    64.872663        59.653859        1.006133   
std      14.675113    14.822135    19.118228        19.495463        1.003949   
min       0.000000     0.000000     0.000000         0.000000        0.000000   
25%      60.140000    58.120000    51.770000        46.470000        0.000000   
50%      69.920000    67.860000    65.460000        59.790000        1.000000   
75%      79.950000    78.000000    78.520000        73.030000        2.000000   
max     100.000000   100.000000   100.000000       100.000000       10.000000   

          Backlogs          DSA         Lang  
count  8805.000000  8805.000000  8805.000000  
mean      0.508234    64.723638     2.008518  
std       0.732098    19.262833     1.434404  
min       0.000000     0.000000     0.000000  
25%       0.000000    51.770000     1.000000  
50%       0.000000    64.670000     2.000000  
75%       1.000000    78.160000     3.000000  
max      10.000000   100.000000    10.000000

In [34]:
#a = dataset.select_dtypes(include=['int64', 'float64'])   understanding the code 



In [35]:
dataset.head() # to check that the missing dataset is filled or not 

Tenth  Twelfth  CGPA  Internships  Projects  Aptitude  Soft skills  \
9484  60.08    86.18  6.75          0.0       5.0     69.41        81.52   
7764  89.68    83.35  7.21          1.0       2.0     71.47        95.75   
5422  84.26    56.42  7.89          0.0       2.0     78.51        83.03   
5163  75.16    81.42  7.61          1.0       1.0     62.02        89.05   
375   67.33    54.50  7.65          0.0       6.0     81.88        69.28   

      Leadership  Extracurricular  Certifications  Backlogs    DSA  Lang  
9484       47.27            38.55             0.0       1.0  55.51   2.0  
7764       68.70            61.01             0.0       0.0  36.63   2.0  
5422       66.48            18.41             1.0       1.0  47.85   2.0  
5163       32.18            47.30             1.0       1.0  72.52   2.0  
375        44.53            56.13             0.0       0.0  65.09   1.0

In [36]:
dataset.describe()

Tenth      Twelfth         CGPA  Internships     Projects  \
count  8805.000000  8805.000000  8805.000000  8805.000000  8805.000000   
mean     74.835295    73.209646     6.984544     1.011811     1.987621   
std      10.113122    11.062912     1.005210     1.000952     1.413235   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      68.110000    65.840000     6.290000     0.000000     1.000000   
50%      74.860000    73.230000     6.990000     1.000000     2.000000   
75%      81.630000    80.750000     7.670000     2.000000     3.000000   
max     100.000000   100.000000    10.000000    10.000000    10.000000   

          Aptitude  Soft skills   Leadership  Extracurricular  Certifications  \
count  8805.000000  8805.000000  8805.000000      8805.000000     8805.000000   
mean     69.901691    67.818410    64.872663        59.653859        1.006133   
std      14.675113    14.822135    19.118228        19.495463        1.003949   
min       0.000000     0.000000     0.000000         0.000000        0.000000   
25%      60.140000    58.120000    51.770000        46.470000        0.000000   
50%      69.920000    67.860000    65.460000        59.790000        1.000000   
75%      79.950000    78.000000    78.520000        73.030000        2.000000   
max     100.000000   100.000000   100.000000       100.000000       10.000000   

          Backlogs          DSA         Lang  
count  8805.000000  8805.000000  8805.000000  
mean      0.508234    64.723638     2.008518  
std       0.732098    19.262833     1.434404  
min       0.000000     0.000000     0.000000  
25%       0.000000    51.770000     1.000000  
50%       0.000000    64.670000     2.000000  
75%       1.000000    78.160000     3.000000  
max      10.000000   100.000000    10.000000

## scikit- learn Design

##### primarly there are three types of objects in it.
1. Estimators - it estimates some parameters based on the given dataset ex- imputer()
                 It has a fit() method and transform method .
   fit method - fits the dataset and calculates internal parameters .
 2. Transfromers -  transform method takes input and returns output based on the learning from fit().
                    it also has a convenience function called fit_transform() which fits and then transforms .
3. Predictors - Linear regression model is an example of predictors. fit() and predicte() are two common function . it also gives score() function      which will evaluate the predictions .

## Feature Scaling

 Primarily, two types of feature scaling methods :
1. Min-max scaling (Normalization)
   (value - min)/(max - min)
   Sklearn provides a class called MinMaxScaler for this

2. Standardization 
   (value - mean)/std
   Sklearn provides a class called StandardScaler for this


## Creating a Pipeline

In [37]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    # .........  add as many you want in your pipeline
    ('std_scaler', StandardScaler()),
])

In [38]:
dataset_num_tr = my_pipeline.fit_transform(dataset_tr)

In [39]:
dataset_num_tr

array([[-1.45910749,  1.17248429, -0.23334171, ...,  0.67176008,
        -0.47833883, -0.00593861],
       [ 1.46794904,  0.91666009,  0.22430028, ..., -0.69425551,
        -1.45852032, -0.00593861],
       [ 0.93198126, -1.51773769,  0.90081453, ...,  0.67176008,
        -0.8760184 , -0.00593861],
       ...,
       [-0.22796378, -0.589358  , -0.36267532, ...,  0.67176008,
         1.83142147, -0.00593861],
       [ 1.07635634,  0.35438923, -1.53662652, ..., -0.69425551,
        -0.22965931, -0.00593861],
       [-0.11127707, -0.68517908,  0.97045571, ...,  0.67176008,
        -0.5349277 , -1.4003251 ]], shape=(8805, 13))

In [40]:
dataset_num_tr.shape

(8805, 13)

## Slecting a Desired model for Placement Prediction

In [41]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
#model = DecisionTreeRegressor()
#model = LinearRegression()
model = RandomForestRegressor()
model.fit(dataset_num_tr, dataset_labels)

RandomForestRegressor()

In [42]:
#print(dataset)


In [43]:
#some_data = dataset.iloc[10:15]

some_data = pd.DataFrame({
    "Tenth": [89, 97.4],
    "Twelfth": [79, 95],
    "CGPA": [6.82, 10.00],
    "Internships": [1, 9],
    "Projects": [2, 8],
    "Aptitude": [50, 100],
    "Soft skills": [4, 8],
    "Leadership": [6, 9],
    "Extracurricular": [2, 7],
    "Certifications": [2, 8],
    "Backlogs": [0, 7],
    "DSA": [20, 90],
    "Lang": [1, 5]
})

In [44]:
print(some_data)

   Tenth  Twelfth   CGPA  Internships  Projects  Aptitude  Soft skills  \
0   89.0       79   6.82            1         2        50            4   
1   97.4       95  10.00            9         8       100            8   

   Leadership  Extracurricular  Certifications  Backlogs  DSA  Lang  
0           6                2               2         0   20     1  
1           9                7               8         7   90     5  


In [45]:
#some_labels = dataset_labels.iloc[10:15]


In [46]:
some_data = some_data[my_pipeline.feature_names_in_]
prepared_data = my_pipeline.transform(some_data)

In [47]:
model.predict(prepared_data)

array([70.46661279, 78.10913173])

In [48]:
#list(some_labels)

## Evaluating the model 

In [49]:
from sklearn.metrics import mean_squared_error #error bata rha hai 
dataset_predictions = model.predict(dataset_num_tr)
mse = mean_squared_error(dataset_labels, dataset_predictions)
rmse = np.sqrt(mse)

In [50]:
rmse #0.00000000000000000000000000000006884604263747013

np.float64(0.3164911336516823)

## Using better evalaution technique - cross validation

In [51]:
# 1 2 3 4 5 6 7 8 9 10 
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, dataset_num_tr, dataset_labels, scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

In [52]:
rmse_scores

array([0.81096655, 0.80406057, 0.85378703, 0.82170806, 0.83000927,
       0.82307602, 0.86807432, 0.81147867, 0.82019884, 1.13958208])

In [53]:
def print_scores(scores):
     print("Scores:", scores)
     print("Mean:", scores.mean())
     print("Standard deviation:", scores.std())
    

In [54]:
print_scores(rmse_scores) #Mean: 3.1094631438138847
#Standard deviation: 0.07771072810799753

Scores: [0.81096655 0.80406057 0.85378703 0.82170806 0.83000927 0.82307602
 0.86807432 0.81147867 0.82019884 1.13958208]
Mean: 0.8582941408048637
Standard deviation: 0.09562524935748141


## Saving the model

In [60]:
import joblib

# Save preprocessing pipeline
joblib.dump(my_pipeline, "pipeline.joblib")



['pipeline.joblib']

In [61]:
# Save trained model
#joblib.dump(model, "Placement.joblib")


## Testing the model on test data

In [ ]:
#X_test = strat_test_set.drop("Probability2", axis=1)
#X_test = X_test.drop(columns='Branch')
#Y_test = strat_test_set["Probability2"].copy()
#X_test_prepared = my_pipeline.transform(X_test)
#final_predictions = model.predict(X_test_prepared)
#final_mse = mean_squared_error(Y_test, final_predictions)
#final_rmse = np.sqrt(final_mse)

In [ ]:
#final_rmse

In [ ]:
#print(list(final_predictions), list(Y_test))

In [ ]:
#prepared_data